###
POST http://localhost:5000/categories
Content-Type: application/json

{
    "name": "Makanan"
}

###
GET http://localhost:5000/categories

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 01",
    "price": 20000
}

###
GET http://localhost:5000/products

###
GET http://localhost:5000/products/1

###
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
    "name": "Product 02 update",
    "price": 30000
}

###
DELETE  http://localhost:5000/products/1